### ISSUE TITLE
Feature Request: Support non-author github repo navigation

### ISSUE THREAD

**Issue by mericsson** [ajhenry/goto#18]
Nice work here! 🎉 -- Apologies in advance if you don't want feature requests as issues, feel free to close. :)

Ideally, I can use this to automatically clone github repos where I am not the author if full path is given. Hope that makes sense, thanks!

## Desired behavior:

`goto ajhenry/goto` it should clone this github project into a new directory `${dev-home}/ajhenry/goto`.

## Actual behavior:

```
➜  ~ goto ajhenry/goto
No paths found for ajhenry/goto
No repos found for ajhenry/goto
✔ /Users/mericsson/dev/ajhenry/goto doesn't exist, do you want to create it? … no / yes
```

**Comment by ajhenry** [comment]
Hey thanks for the feature request! This was actually a functionality I already needed and have been using for a few days to see if the flow made sense.

There were a few ways I was thinking about having to deal with repos that aren't "yours" or part of any orgs that you're not in.

If I enter something like `ajhenry/goto` this is way I'm handling it now:

- First searches locally, if the directory exists, go to it
- Next search github, if there is a repo with that exact repo path, clone and go to it
- If there isn't one, provide the search results
- If there are no search results, then it asks for you to create the directory

![terminal](https://user-images.githubusercontent.com/24923406/184560763-74b1a5e2-ce18-426f-97fe-0ab01a52fcf3.svg)

**Comment by mericsson** [comment]
Nice! Sgtm! :shipit:
